/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* To migrate to environment variables, use import.meta.env.VITE_SUPABASE_URL etc. */
/* See .env.example at the project root for the expected variable names. */

export const projectId = "dzksapjocjcoseougoqb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6a3NhcGpvY2pjb3Nlb3Vnb3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNjAyMzYsImV4cCI6MjA4NzYzNjIzNn0.8XCyVK7MUeejWDwuYT2jmLSqCf4J6z2nroUT5SauVnU"
